version: "3.8"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mazhugasergei
      - MONGO_INITDB_ROOT_PASSWORD=12312131231213

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mazhugasergei
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12312131231213
      - ME_CONFIG_BASICAUTH_USERNAME=mazhugasergei
      - ME_CONFIG_BASICAUTH_PASSWORD=12312131231213
      - ME_CONFIG_MONGODB_URL=mongodb://mazhugasergei:12312131231213@mongo:27017
